#!/usr/bin/env bash
# Copyright (c) Joseph Hale, 2026
# SPDX-License-Identifier: MPL-2.0

function configure() {
	local path
	path="$CACHE/sgconfig${1:+.$1}.yml"
	write
	write_settings "${1:-}" "$path"
	echo "$path"
}

function write() {
	local rule language
	reset
	catalogue | while read -r rule language; do
		write_matcher "$rule" "$language"
		write_snippets "$rule" "$language"
	done
}

function reset() {
	rm -rf "${CACHE:?}/rules" "${CACHE:?}/rule-tests"
	mkdir -p "$CACHE/rules" "$CACHE/rule-tests"
}

function write_matcher() {
	matcher "$1" "$2" >"$CACHE/rules/$(basename "$1" .yml).$2.yml"
}

function write_snippets() {
	snippets "$1" "$2" >"$CACHE/rule-tests/$(basename "$1" .yml).$2-test.yml"
}

function write_settings() {
	settings "$1" >"$2"
}
