#!/usr/bin/env bash
# Copyright (c) Joseph Hale, 2026
# SPDX-License-Identifier: MPL-2.0

function catalogue() {
	local rule language
	for rule in "$ROOT"/rules/*.yml; do
		for language in $(languages "$rule"); do
			echo "$rule $language"
		done
	done
}

function languages() {
	local tests
	tests="$(snippets_for "$1")"
	if [[ -f "$tests" ]]; then
		"$YQ" 'keys | .[]' "$tests"
	fi
}

function snippets_for() {
	echo "$ROOT/rule-tests/$(basename "$1")"
}

function matcher() {
	LANGUAGE="$2" BODY="$(body "$1" "$2")" "$YQ" '{
		"id": .id + "." + strenv(LANGUAGE),
		"language": strenv(LANGUAGE),
		"severity": .severity,
		"message": .message,
		"rule": (strenv(BODY) | from_json)
	} | (... style="")' "$1"
}

function body() {
	LANGUAGE="$2" "$YQ" -o=json "$1" | LANGUAGE="$2" "$JQ" -c '
		[ if ((.languages[env.LANGUAGE] // {}) | has("except"))
		  then .rule
		  else (.languages[env.LANGUAGE] // .rule) end ]
		+ ([.except, .languages[env.LANGUAGE].except] | map(select(. != null)) | map({not: .}))
		| if length == 1 then .[0] else {all: .} end
	'
}

function snippets() {
	ID="$("$YQ" '.id' "$1")" LANGUAGE="$2" "$YQ" '{
		"id": strenv(ID) + "." + strenv(LANGUAGE),
		"valid": .[strenv(LANGUAGE)].valid,
		"invalid": .[strenv(LANGUAGE)].invalid
	}' "$(snippets_for "$1")"
}
