#!/usr/bin/env bash
# Copyright (c) Joseph Hale, 2026
# SPDX-License-Identifier: MPL-2.0

function catalogue() {
	local rule language
	for rule in "$ROOT"/rules/*.yml; do
		for language in $(languages "$rule"); do
			echo "$rule $language"
		done
	done
}

function languages() {
	local tests
	tests="$(snippets_for "$1")"
	if [[ -f "$tests" ]]; then
		"$YQ" 'keys | .[]' "$tests"
	fi
}

function snippets_for() {
	echo "$ROOT/rule-tests/$(basename "$1")"
}

function matcher() {
	LANGUAGE="$2" BODY="$(body "$1" "$2")" "$YQ" '{
		"id": .id + "." + strenv(LANGUAGE),
		"language": strenv(LANGUAGE),
		"severity": .severity,
		"message": .message,
		"rule": (strenv(BODY) | from_json)
	} | (... style="")' "$1"
}

function body() {
	local default
	default="$(query "$1")"
	if [[ "$(LANGUAGE="$2" "$YQ" '.languages[strenv(LANGUAGE)].except // ""' "$1")" == "" ]]; then
		LANGUAGE="$2" DEFAULT="$default" "$YQ" -o=json -I=0 '.languages[strenv(LANGUAGE)] // (strenv(DEFAULT) | from_json)' "$1"
	else
		LANGUAGE="$2" DEFAULT="$default" "$YQ" -o=json -I=0 '{"all": [(strenv(DEFAULT) | from_json), {"not": .languages[strenv(LANGUAGE)].except}]}' "$1"
	fi
}

function query() {
	if [[ "$("$YQ" '.except // ""' "$1")" == "" ]]; then
		"$YQ" -o=json -I=0 '.rule' "$1"
	else
		"$YQ" -o=json -I=0 '{"all": [.rule, {"not": .except}]}' "$1"
	fi
}

function snippets() {
	ID="$("$YQ" '.id' "$1")" LANGUAGE="$2" "$YQ" '{
		"id": strenv(ID) + "." + strenv(LANGUAGE),
		"valid": .[strenv(LANGUAGE)].valid,
		"invalid": .[strenv(LANGUAGE)].invalid
	}' "$(snippets_for "$1")"
}
