#!/usr/bin/env bash
# Copyright (c) Joseph Hale, 2026
# SPDX-License-Identifier: MPL-2.0

function settings() {
	printf 'ruleDirs:\n  - %s/rules\n' "$CACHE"
	printf 'testConfigs:\n  - testDir: %s/rule-tests\n' "$CACHE"
	if [[ -n "$1" ]]; then
		printf 'languageGlobs:\n  %s: ["*"]\n' "$1"
	fi
	printf 'customLanguages:\n'
	declaration gotmpl
}

function declaration() {
	printf '  %s:\n' "$1"
	printf '    libraryPath: %s\n' "$(library "$1")"
	printf '    extensions: [%s]\n' "$1"
	printf '    expandoChar: _\n'
}
