[tools]
"aqua:hashicorp/copywrite" = "latest"
"github:thehale/bashorder" = "latest"
actionlint = "latest"
bats = "1.14.0"
markdownlint-cli2 = "latest"
shellcheck = "latest"
shfmt = "latest"
yamlfmt = "latest"
zizmor = "latest"

rust = { version = "1.98.1", components = ["rustfmt", "clippy"] }

[settings]
minimum_release_age_excludes = ["github:thehale/bashorder"]
