[tools]
"aqua:hashicorp/copywrite" = "latest"
"github:thehale/bashorder" = "latest"
actionlint = "latest"
bats = "1.14.0"
markdownlint-cli2 = "latest"
rust = "1.98.1"
shellcheck = "latest"
shfmt = "latest"
yamlfmt = "latest"
zizmor = "latest"

[settings]
minimum_release_age_excludes = ["github:thehale/bashorder"]
